publication_name: "Dependency Forming Medicines"
publication_sub_name: "England 2015/16 to 2022/23"
publication_date: "7 September 2023"
responsible_statistician: "Graham Platten"
stats_survey_link: "https://online1.snapsurveys.com/Official_Statistics_Feedback"
fy: "2022/23"
costs_items_excel: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/dfm/dfm_2022_2023_costs_and_items_v001.xlsx"
demographics_excel: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/dfm/dfm_2022_2023_patient_demographics_v001.xlsx"
background_link: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/dfm/dfm_background_info_methodology_v001.html"
