publication_name: "Dependency-Forming Medicines"
publication_sub_name: "England 2015/16 to 2023/24"
publication_date: "5 September 2024"
responsible_statistician: "Graham Platten"
stats_survey_link: "https://online1.snapsurveys.com/Official_Statistics_Feedback"
fy: "2023/24"
costs_items_excel: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/dfm/dfm_2023_2024_costs_and_items_v001.xlsx"
demographics_excel: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/dfm/dfm_2023_2024_patient_demographics_v001.xlsx"
background_link: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/dfm/dfm_background_info_methodology_v001.html"
sql_schema: "OST"
sql_table_name: "DFM_FACT_CATEGORY_202408"
