publication_name: "Prescription Cost Analysis"
publication_sub_name: "England 2022/23"
publication_date: "8 June 2023"
responsible_statistician: "Graham Platten"
stats_survey_link: "https://online1.snapsurveys.com/Official_Statistics_Feedback"
fy: "2022/23"
